### ISSUE TITLE
QCloud.Weapp.SDK.Documentation\QCloud.Weapp.SDK.Documentation.shfbproj: 未找到此项目类型所基于的应用程序

### ISSUE THREAD

**Issue by iterator-zh** [tencentyun/wafer-csharp-server-sdk#3]
vs2015打开wafer-csharp-server-sdk项目出现问题，	QCloud.Weapp.SDK.Documentation\QCloud.Weapp.SDK.Documentation.shfbproj: 未找到此项目类型所基于的应用程序。请尝试以下链接以获取更多信息: http://go.microsoft.com/fwlink/?LinkId=659044&projecttype=7CF6DF6D-3B04-46F8-A40B-537D21BCA0B4

请问这是什么情况？
![0b yb8e8z2hcthw _99uv](https://cloud.githubusercontent.com/assets/26211731/23828744/52486e46-0716-11e7-87bb-9179df8de7db.jpg)

**Comment by techird** [comment]
这个项目是用于输出 SDK 文档的。开发者可以无需安装。如果有兴趣的话可以安装 [SHFB](https://github.com/EWSoftware/SHFB) 来支持哈。
